### ISSUE TITLE
Decide on initial pricing for Linkdrop PRO

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#101]
# Description

We need to decide on the pricing model, means of payment and visualization form for the first version of Linkdrop PRO

# Subtasks included

- [x] Decide on pricing model
- [x] Decide on means of payment
- [x] Final mock-ups of payment flow
- [x] Final mock-up of "pricing model" explained

# Definition of done

Above subtasks are done, and a new implementation task is created and assigned.

# Reviewer

@artignatyev @Dobrokhvalov

**Comment by Kisgus** [comment]
Pricing model and means of payment:

https://docs.google.com/spreadsheets/d/1_JN4oKG-sVXIaiDFOZq5TJMf9tRcJJBzyMBVRVPLaWg/edit#gid=0
