### ISSUE TITLE
Add connection to MongoDB

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#109]
# Description
Add connection to MongoDB, and make sure the same tx is not being submitted twice

# Subtasks included

- [x] Add MongoDB connection
- [x] Create new ClaimTx model
- [x] Add logic to prevent double tx

# Definition of done
Submitted transactions are saved to DB, the same tx is not submitted twice

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/pull/114
