### ISSUE TITLE
make a research for CI/CD for front-end part of application

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#122]
# Subtasks included

- [x] get hetzner vps for testing
- [x] find best solutions for assets build process
- [x] integrate netlify to github
- [x] work with linkdrop-ui-kit to build before applications start
- [x] work with app-demo
- [x] work with app-claim
