### ISSUE TITLE
Contracts Refactoring

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#137]
# Tasks

- [x] rename sender -> linkdropMasterAddress
- [x] remove approve functionality (for now let's remove all approve functionality)

- [x] **Factory Contracts**
put factory contracts in Factory directory
  - CloneFactory
  - LinkdropFactoryCommon 
  - LinkdropFactoryERC20
  - LinkdropFactoryERC721
  - (Remove dependency from Storage) 

- [x] **Linkdrop Contracts**
 put linkdrop contracts in Linkdrop directory:
	- LinkdropСommon (Merge with Storage)
	- LinkdropERC20
	- LinkdropERC721
	- LinkdropMasterCopy

- [x] Make sure all comments are matching with params. 

# Reviewer
@Dobrokhvalov 

# Dependencies
Before starting this task, ETH+Tokens task should be implemented

**Comment by amiromayer** [comment]
Done in #142
