### ISSUE TITLE
Add Approve Linkdrop Contract Interface

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#139]
# Description
As a user, I want to have an option to approve a proxy contract to withdraw tokens from my account. This will allow users to keep tokens in their accounts, while not to disclose their private key. 

**Implementation details**
Add new interfaces for linkdrop to use approve (instead of top-up) funding method. 
This will result in different functions, as approve requires more arguments: linkdropMasterKey + sender vs. only linkdropMasterKey)

**Not in scope of the current issue:**
- In future SDK should generate different links for different linkdrop interfaces (top-up vs approve)
- Depending on the information provided, the server should also call different methods of the linkdrop contract. 

# Subtasks included
Add the following approve linkdrop interfaces to smart contracts:
- [x] ERC20 (proxy and factory)
- [x] ERC721 (proxy and factory)
- [x] Test ERC20 functionality (approve pattern)
- [x] Test ERC721 functionality (approve pattern)

# Definition of done
Users are able to choose between top-up and approve linkdrop funding methods. 

# Dependency
Refactoring should be implemented first - https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/137

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/pull/146
