### ISSUE TITLE
Add claim function to Factory Contract

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#15]
# Description

Add `claim` function to the Factory Contract so that Factory contract should: 

1) deploy Proxy Contract if it's not deployed yet 
2) call `claim` function of a Proxy Contract 

# Subtasks included
- [x] Factory contract has claim function
- [x] Tokens can be claimed for the not deployed yet proxy contracts 
- [x] Tokens can be claimed for the existing proxy contracts 
- [x] Tests

# Definition of done
Implemented all the subtasks.

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
@Dobrokhvalov Implemented in #17
