### ISSUE TITLE
Server endpoint for claim ETH+ERC20 

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#16]
# Description

## Claim ETH+ERC20 linkdrop

POST /linkdrops/claim

**Params**

- `sender`: sender key address, e.g. 0x1234...ff
- `receiver`: destination address
- `linkId`: Ethereum address belonging to the link key
- `senderSignature`: ECDSA signature signed by sender (contained in claim link)
- `receiverSignature`: ECDSA signature signed by receiver using link key
- `token`: ERC20 token address, 0x000...000 for ether
- `tokenAmount`: token amount in atomic values
- `expirationTime`: link expiration time

**Response**
- `success` - boolean, if the server successfully sent a claim transaction 
- `txHash` - string with transaction hash of the claim transaction

# Subtasks included

- [ ] NodeJs server in `/server` folder
- [ ] Endpoint for claiming ETH+ERC20 
- [ ] Instructions on how to deploy the server in `/server/README`
- [ ] Config file with configurations for Ethereum network and server's private key. The config file should be added to .gitignore, but example file should be provided.   

# Definition of done
It's possible to configure and deploy the claiming server.  
And claim eth+erc20 linkdrop via server call.

# Reviewer
@Dobrokhvalov

**Comment by spacehaz** [comment]
response should include keys:
1. **success (:bool)**
_success: false_ means that server cannot finish the request successfully (beacuse of invalid params from browser, etc)
_success: true_ - everything is okay!

2. **data (:obj)**
_data: { transaction_id: '0x000000000...' }_. Data should contain all data needed for client to change the state of application

3. **errors (:array)**
_errors: ['SENDER_KEY_ADDRESS_INVALID']_ means that server received invalid key from user
_errors: ['SENDER_KEY_ADDRESS_INVALID', 'DESTINATIONS_INVALID']_ means that there are two different errors
the template for error: constant style (uppercase), snake-case, '_INVALID' suffix for keys that are invalid, '_NEEDED' suffix for keys that are required but not found

4. **meta (:obj)**
_meta: { some_important_information: [ { title: 'bla' } ] }_. Some extra data that doesnt refer to original request, but can be useful for user. 99% of usage - GET requests


so the response should look like that example:

1. **successful**
```
{
  success: true,
  data: {
    bla: 'bla-bla',
    foo: true
  }
}
```

2. **failed**
```
{
  success: false,
  errors: ['BLA_BLA_INVALID']
}

```
3. **with meta:**

```
{
  success: true,
  data: {
    bla: 'bla-bla',
    foo: true
  },
  meta: {
    extra: [1, 23, 34, 4]
  }
}
```

**Comment by Dobrokhvalov** [comment]
@spacehaz Looking good! Just one minor comment: I'd propose to use `transaction_hash` instead of `transaction_id`

**Comment by spacehaz** [comment]
@Dobrokhvalov yes, exactly! anyway i just wanted to reflect format, all keys we can get from your initial post

**Comment by amiromayer** [comment]
@Dobrokhvalov Implemented in #51
