### ISSUE TITLE
Add separate signing keys along with master key

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#163]
# Description
Users should be able to add/delete several signing keys along with master key

# Subtasks included

- [x] Add new functionality to contracts
- [x] Change current tests to be compatible with new functionality
- [x] Add new tests for new functionality

# Definition of done
All tests are passed, users are able to add separate signing keys

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Implemented in #164
