### ISSUE TITLE
add metamask detection to linkdrop-demo page 

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#171]
# Subtasks included

- [x] add metamask detection of current account
- [x] add assets detection on current wallet
- [x] add input with amount
- [x] finish assets send logic
