### ISSUE TITLE
Add upgradability to contracts

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#174]
# Description
Users should be able to upgrade their contracts

# Subtasks included

- [x] Add function to update the `masterCopy` address to the `Factory` contract
- [x] Add function for users to `upgrade` their proxy contracts
- [x] Make sure `verifyLinkdropSignerSignature` function also checks the contracts version for which it was signed
- [x] Cover new functionality with tests 
- [x] Refactor code
- [x] Refactor all previous test so that they are compatible with updated contracts

# Definition of done
Users are able to initiate the upgradability process on their own

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Implemented in #177
