### ISSUE TITLE
Add address of mastercopy instead of bytecode for upgradability

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#190]
# Description
Currently `bytecode` is being passed as a param to `updateBytecode` function. 
Pass `masterCopy` address instead and calculate the needed bytecode for proxy instantiation on-chain.
Also remove `initcode` from being passed to the factory constructor and rather hardcode it, since it's never going to change. 
Make sure `deployProxy` is called either by `linkdropMaster` himself (`msg.sender`) or internally by Factory contract to prevent unneeded proxy creation on behalf of users

# Subtasks included

- [x] Update `updateBytecode` function (calculate bytecode on-chain)
- [x] Update constructor (hardcode `initcode`, pass `masterCopy` address)
- [x] Change `deployProxy`
- [x] Refactor all tests
- [x] Prepare and make sure everything is compatible with new functionality
- [x] Add master copy destruction prevention (parity bug)
# Definition of done

# Reviewer
@Dobrokhvalov
