### ISSUE TITLE
Move front-end apps into one directory 

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#193]
# Description
For better project structure, move all front-end apps into single directory - `apps`

# Subtasks included
Move the following apps: 
- [x] app-claim
- [x] app-landing
- [x] linkdrop-commons? 
- [x] linkdrop-ui-kit
- [x] move current README.md to apps/README.md

Remove:
- [x] `app-send` directory

# Definition of done
All subtasks are implemented

# Reviewer
@Dobrokhvalov
