### ISSUE TITLE
Onboarding to Linkdrop backend

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#2]
# Subtasks

- [x] Review mock-ups
- [x] Take part in technical description meeting
- [x] Ask questions about any unclear aspects
- [x] Create dedicated tasks needed for linkdrop backend
