### ISSUE TITLE
ERC721 Linkdrop Deploy via Terminal

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#20]
# Description
In order to make testing and integrating front-end with back-end easier, add linkdrop deployment scripts, so that it's possible to deploy linkdrop campaigns and generate claim links via command line. 

Script source files should be in the ‘scripts’ folder

**Configs** 
The config file (the same as in https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16) should contain the following params under `linkdrop` key:  
- `nft`: address of ERC721 token
- `nftIds`: list of ids to generate links, e.g.  [1,2,3,4]   
- `senderPrivateKey`: sender's private key, the sender should have positive token balance in order to deploy a linkdrop 
- `factoryAddress`: address of the Factory Contract
- `linksNumber`: number of links to generate 
- `networkId`: Ethereum network id, e.g. "1"  for Mainnet
- `jsonRpcUrl`: Url of JSON-RPC provider

**Commands**
If the Factory Contract is not deployed, the script execution aborts with a meaningful message. 

For testing NFT: 
`yarn deploy erc721`
The command deploys new ERC721 token and updates the config file accordingly (`nft address`) 

`yarn linkdrop erc721`
The command: 
- precomputes proxy address using CREATE2 
- transfers tokens needed (according to linkdrop params) from senders to the proxy address
- generates links in a CSV file `scripts/output/links-erc721.csv` 

# Subtasks included
- [x] Example config for a test network (e.g. `config.json.rinkeby`)
- [x] Deploy erc721 token command
- [x] Deploy Linkdrop erc721 command

# Definition of done
Valid claim links with ERC721 token can be generated using terminal commands.  

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
@Dobrokhvalov Implemented in #73
