### ISSUE TITLE
ERC20 Linkdrop Deploy via Terminal 

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#21]
# Description
In order to make testing and integrating front-end with back-end easier, add linkdrop deployment scripts, so that it's possible to deploy linkdrop campaigns and generate claim links via command line. 

Script source files should be in the ‘scripts’ folder

**Configs** 
The config file (the same as in https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16) should contain the following params under `linkdrop` key:  
- `token`: linkdrop's ERC20 token address
- `amount`: the number of tokens per link 
- `senderPrivateKey`: sender's private key, the sender should have positive token balance in order to deploy a linkdrop 
- `factoryAddress`: address of the Factory Contract
- `linksNumber`: number of links to generate 
- `networkId`: Ethereum network id, e.g. "1"  for Mainnet
- `jsonRpcUrl`: Url of JSON-RPC provider

**Commands**
`yarn linkdrop erc20`
The command: 
- precomputes proxy address using CREATE2 
- transfers tokens needed (according to linkdrop params) from senders to the proxy address
- generates links in a CSV file `scripts/output/links.csv` 

If the Factory Contract is not deployed, the script execution aborts with a meaningful message. 
If the sender doesn't have tokens, the script execution aborts with a meaningful message. 

For testing ERC20: 
`yarn deploy erc20`
Deploys a mock ERC20 token, where the linkdrop sender is an owner of the tokens needed for linkdrop  

# Subtasks included
- [ ] Example config for a test network (e.g. `config.json.rinkeby`)
- [ ] Deploy erc20 token command
- [ ] Deploy Linkdrop erc20 command

# Definition of done
Factory Contract and valid claim links can be generated using terminal commands.  

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
implemented in #51

**Comment by Dobrokhvalov** [comment]
implemented in #51
