### ISSUE TITLE
Prepare contracts for Dashboard

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#266]
# Description
Change contracts for Dashboard

# Subtasks included

- [x]  1 campaign = 1 contract (change CREATE2)
- [x] Only approve pattern is needed
- [x] Add ethers withdraw
- [x] Make contracts pausable
- [x] Specify fee (via RelayerRegistry whitelist)
- [x] Remove chainId and version from url params
- [x] Unit test all the new functionality added

# Definition of done

# Reviewer
@Dobrokhvalov
