### ISSUE TITLE
Whitelabel claiming page

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#32]
# Description

Several users of eth2 and volca.tech has requested to custom the claiming page flow

# Subtasks included

- [x] Split claiming flow into dedicated component suitable for support white-label solutions
- [x] Split claiming story-book into dedicated component 

# Definition of done

- [ ] First custom claiming page is delivered

# Reviewer

@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
@Kisgus I think we can close this issue until we have a particular customer request for it. 
However, @spacehaz already took this into account while working on front-end.
