### ISSUE TITLE
Paid access to files & hosted files.

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#34]
# Description

Allow users to get for access to a file, which can be 1. uploaded to IPFS via our platform or 2. shown behind a link (e.g. get paid for mega.nz file pw).

# Subtasks included

- [x] write user story
- [x] make design: https://www.figma.com/file/cAZC7IPUn1N1soraUWLmIxCw/Linkdrop-Pro?node-id=57%3A316

# Definition of done

- [ ] Feedback by the team if we need this or not.

# Reviewer

**Comment by Dobrokhvalov** [comment]
I like the idea, but not sure how it's different from https://enzypt.io/. Also would love to know how enzypt works under the hood

**Comment by Kisgus** [comment]
Moved to product repo
