### ISSUE TITLE
Linkdrop PRO Analytics

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#38]
# Description

We need to define:

- Data collected
- Data visible

# Subtasks included

- [x] Create list of what we can collect
- [x] Decide on which things and how we will collect for Analytics page  v1
- [ ] Implement front-end
- [ ] Implement back-end

# Definition of done

- [ ] The desired analytics are collected and presented in a nice format with pretty visualizations

# After done

- [ ] Open new issue on asking customers on their needs for analytics

# Reviewer

@Kisgus

**Comment by Dobrokhvalov** [comment]
I propose split the issue in 3: 
- define what to do (done)
- create mock ups
- implement in dashboard

**Comment by Kisgus** [comment]
Agreed

**Comment by artignatyev** [comment]
Issue with mockups we already have -> #50. We can split this issue in two: dashboard mockups and for analytics

**Comment by Kisgus** [comment]
Okay cool. I will close this issue, as this is this covers the "define what to do". Then I create implement dashboard, and implement analytics issues
