### ISSUE TITLE
claim data (wallet id, etc) from trustwallet on mobile version of tokens claim

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#44]
# Subtasks included

- [x] metamask logic on desktop
- [x] trustwallet logic on mobile
- [x] logic for wallet change
- [x] add web3-react

**Comment by Dobrokhvalov** [comment]
implemented in #54
