### ISSUE TITLE
Include Terms of Use and Privacy Policy

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#46]
# Description

Include above in send and receive flow.

# Subtasks included

- [x] Include policies in mock-ups
- [x] Get policies
- [x] Link to the policies in implemented flow

# Definition of done

All users sending and receiving will confirm to the terms / policies.

# Reviewer

**Comment by Kisgus** [comment]
Review needed, preferably via a call. Putting into review, and assigning @Dobrokhvalov

**Comment by Kisgus** [comment]
Documents are ready @spacehaz @artignatyev please DM for hand-over

**Comment by Kisgus** [comment]
## Ooops, update date and link to Privacy Policy and Terms of Use linkdrop.io URL


**Terms of Service**

- [ ] https://docs.google.com/document/d/1EBdN-k6kXHQ0lnWWYKz1TxOaYok-DOZMepUqoSoE1xw/edit#

**Privacy Policy**

- [ ] https://docs.google.com/document/d/1ltTC1AdnmHRAHX8q4Enh08C4ePAfcw84laC3x70V3Ig/edit#

**Comment by Kisgus** [comment]
Done
