### ISSUE TITLE
Extract all linkdrop core code in scripts into linkdrop-sdk

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#48]
# Description
Extract the linkdrop functions from scripts into stand-alone SDK. Linkdrop SDK will be used in front-end and scripts in order to generate and send linkdrops. 

# Subtasks included
Extract the following functions in the sdk: 
- [ ] Precompute address to send tokens
- [ ] Generate claim link
- [ ] Claim link (via call to server end-point)

# Definition of done
Stand-alone linkdrop-sdk is implemented, that can be used in the front-end app.

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
implemented in #51
