### ISSUE TITLE
Linkdrop Demo mockups

### ISSUE THREAD

**Issue by artignatyev** [LinkdropProtocol/linkdrop-monorepo#49]
# Description

Mockups of widget with the demo of sending links and simple landing page.

# Subtasks included

- [x] Widget with the demo of sending links
- [x] Simple landing page
- [x] Check text and wording (Chris)

# Definition of done

Above screens are done, fully handed-over, and the implementation has started.

# Reviewer

@Dobrokhvalov, @Kisgus
