### ISSUE TITLE
Linkswap concept and mock-ups

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#52]
# Description

We have discussed a lot about the possibility of extending Linkdrop and Linkdro PRO with Linkswap functionality

# Subtasks included

- [ ] Write up technical description
- [x] Make different conceptual mock-ups comparing UX
- [ ] Research if and how this is different than https://boxswap.io/
- [ ] Research if and how this provides synergy to https://0x.org/

# Definition of done

Once the sub-tasks are completed, we evaluate if we move further with this new functionality

# Reviewer

@Kisgus

**Comment by seichris** [comment]
Made some mockups in our Linkdrop PRO design board.

**Comment by Kisgus** [comment]
Great thanks, I propose to find the time this or next week to have a brief chat about this and "Card" with @Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
I can find some time this or next week, doesn't really matter to me when

**Comment by Kisgus** [comment]
Agreed with Dobrok it will be Monday after stand-up @seichris

**Comment by Kisgus** [comment]
Lets do some more detailed mock-ups of how the link-swap feature will look opened in Linkdrop Webapp on mobile and desktop

**Comment by Kisgus** [comment]
Moved to product feedback repo
