### ISSUE TITLE
Linkdrop Integration Brainstrom

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#53]
# Description

For our future collaborations we need better to understand how Linkdrop can add value in integration with other services

# Subtasks included

- [x] Draft concept and mock-ups of imtoken integration, forexample native "referral links"
- [x] Draft concept and mock-ups of linkdrop within localethereum
- [x] Draft concept and mock-ups of linkdrop working with opensea and/or vaulgt
- [x] Any other good ideas for integration or usecases? Feel free to add some

# Definition of done

Subtasks are done, and we evaluate which integrations to prioritize

# Reviewer

@Kisgus

**Comment by Kisgus** [comment]
Will be included in next Thursday Community Call
