### ISSUE TITLE
New improvements to app-landing token share flow

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#56]
# Description
change app-landing according to new ideas and mock-ups of Artyom

# Subtasks included

- [x] new page templates in app-landing
- [x] components improvement in ui-kit
- [x] add mobile phone and tablets media-queries for responsiveness
