### ISSUE TITLE
Deploy linkdrop relayers on cloud for Rinkeby 

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#62]
# Description
Deploy linkdrop relayer on cloud (Digital Ocean VPS instance)

# Subtasks included
- [x] Setup VPS on Digital Ocean
- [x] Buy and setup certificates for *.linkdrop.org
- [x] Update PM2 command 
- [x] Linkdrop relayer for Rinkeby on rinkeby.linkdrop.org

# Definition of done
Public linkdrop relayers are available for Rinkeby and Mainnet

# Reviewer
@Dobrokhvalov
