### ISSUE TITLE
Finish the claiming flow by integrating it with linkdrop-sdk

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#65]
# Description
The mockups for the claiming flow are done. So we need to connect it with linkdrop-sdk, so real claims can be made using front-end app. 

# Subtasks included
- [ ] claim ETH
- [ ] claim ERC20
- [ ] claim ERC721
- [ ] correct page for claimed link 
- [ ] correct page for expired link
- [ ] correct page for failed claim

# Definition of done
Linkdrops can be claimed via the app-claiming front-end app.  

# Reviewer
@Dobrokhvalov @spacehaz

**Comment by Dobrokhvalov** [comment]
Moved to https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/93
