### ISSUE TITLE
Host landing and claiming apps

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#66]
# Description
Landing and claming apps should be hosted and available at public URLs. 

# Subtasks included
- [x] choose hosting solution: Github pages / Netlify / etc.
- [x] host landing app
- [x] host claiming app

# Definition of done
The apps are hosted and available publicly. 

# Reviewer
@Dobrokhvalov
