### ISSUE TITLE
Add unit tests for newly created contracts

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#67]
# Description
Add waffle tests to unit test all the functionality in newly created contracts (proxy-factory and top-up patterns)

# Subtasks included

- [x] Test factory - proxy pattern
- [x] Test claiming ether
- [x] Test claiming ERC20
- [x] Test claiming ERC721

# Definition of done
All tests are passed

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
@Dobrokhvalov ✅ in #74
