### ISSUE TITLE
Add README for linkdrop-sdk

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#75]
# Description
External developers should be able to use the linkdrop-sdk just by reading instructions in the repo.  

# Subtasks included
The readme should contain: 
- [x] Short description of the sdk 
- [x] Instructions how to install
- [x] Instructions how to install

# Definition of done
There is an extensive readme on how to install and use the linkdrop-sdk

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
@Dobrokhvalov ✅ in #88
