### ISSUE TITLE
Scripts Minor Refinements

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#81]
# Description
Several tasks to make work with scripts easier and enjoyable.  

# Subtasks included

- [x] Split commands for claiming eth and erc20. 
- [x] Update config.json.sample
- [x] Update the script's README: short description, how to configure, how to set up, tasks for eth, tasks for erc20, tasks for erc721.  
- [x] Change terminal output from "Successfully claimed tokens" to "Successfully submitted claiming transaction. Please verify the claim status manually."

# Definition of done
Subtasks implemented

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
Proposal for the README structure:

## Short description
Scripts for setting up, deploying, generating and claiming linkdrops. 

## Configure
Config file should be located in ... 
Before running the scripts you need to configure the following: ...
You can copy the configs from configs.json.sample, but make sure to fill in the following params: `sendersPrivateKey`, ...

## General set up
Before generating linkdrops you need to deploy mastercopy contract and factory address: 
```
yarn deploy-factory
yarn deploy-mastercopy
```
After you deployed factory or mastercopy contracts the config file will be updated. **Restart the server after deploying new contracts**

## Generate and claim ETH
To test ETH linkdrops: 

0. Configure amount of ETH to send per link. 
1. Generate links. During link generation, eth needed for claim will be sent to the proxy address. 
```
yarn generate-links-eth
```
2. Claim a link
```
 yarn claim-eth
```

## Generate and claim ERC20
To test ERC20 linkdrops, you need to: 

0. Configure ERC20 token and amount to claim. 

If you don't have any ERC20 tokens, you can deploy a new token by running the command: 
```
yarn deploy-erc20
```
The command updates the config automatically and deploy new ERC20 token and transfers 10^6 of new tokens to the deployer. 

1. Generate links. During link generation, tokens will be sent to the proxy address. 
```
yarn generate-links-erc20
```
2. Claim a link
```
 yarn claim-erc20
```

### Generate and claim ERC721
....

**Comment by amiromayer** [comment]
✅ in #85
