### ISSUE TITLE
Add server checks while claiming tokens

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#86]
# Description
The server should not try to submit claim transactions when parameters are wrong. So the server should call factory contract to check if parameters are valid. 

# Subtasks included

**ETH/ERC20**
- [x] Add checkClaimParams function to Factory contract (+tests)
- [x] Update claim controller to call factory's checkClaimParams function before submitting the tx
- [x] Update the proxy's checkClaimParams to have a check that sender has enough ETH/tokens to do transfer (+tests)

**ERC721**
- [x] Add checkParamsERC721 function to Factory contract (+tests)
- [x] Update claim controller to call the factory's checkParamsERC721 function before submitting the tx
- [x] Update the proxy's checkClaimParamsERC721 to have a check that sender has needed ERC721 token to do transfer (+tests)

NOTE: 
There can be 2 cases: 
a) proxy isn't deployed yet
the factory's checkClaimParams function should check:
  - claim params
  - that the proxy address has enough tokens

b) proxy is deployed
  - factory's checkClaimParams function should call the proxy contract's checkClaimParams

# Definition of done
 Server and contracts are updated with all needed checks.  

# Reviewer
@Dobrokhvalov
