### ISSUE TITLE
Add approve support for ERC20/ERC721

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#87]
# Description
As a customer of linkdrop PRO, I'd feel more secure approving tokens instead of transferring. 
But we should keep the transfer option as well for UX reasons. 

# Subtasks included

**ERC20**
- [x] Proxy and factory contracts support claiming of approved tokens. 
- [x] Add public function to factory displaying total amount available for a proxy (approved+transferred) 
- [x] Add public function to proxy displaying total amount available for a proxy (approved+transferred) 
- [x] Tests added for new functionality. 

The contract should withdraw tokens on the proxy address first.  
If there are not enough tokens on the proxy's balance, the remained amount should be transferred from the sender's balance.

Pseudocode: 
```
function _transfer(amount) {
  // amount of tokens on the proxy's address 
   balance = token.balanceOf(proxy)
  
   // amount approved by sender for proxy  
   approved = token. allowance(sender, proxy)
   tokensAvailable = balance + approved

   // verify that tokens are available for claim
   require(tokensAvailable > amount)
   
  // try to withdraw from proxy first
  if (balance > 0) {
     // how many tokens should be transferred from proxy 
     fromProxyAmount = min(balance, amount)
     amount = amount - fromProxyAmount
     token.transfer(destinationAddr, fromProxyAmount)
  } 
  // send rest from sender's account
  // return if all tokens were already sent by proxy
  if (amount == 0) return 

  //  
  token.transferFrom(sender, destinationAddr, amount)
}
```

**ERC721**
- [x] Proxy and factory contracts support claiming of approved tokens. 
- [x] Add public function to factory displaying if a token is available for the proxy(approved or transferred) 
- [x] Add public function to proxy displaying if a token is available for the proxy(approved or transferred) 
- [x] Tests added for new functionality. 

# Definition of done
Approve support is added for ERC20 and ERC721 tokens

# Reviewer
@Dobrokhvalov
