### ISSUE TITLE
Continue integration for tokens claiming

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#93]
Finish the claiming flow. Get the current dev version, go to app-claim folder, rum dev-server with command `yarn dev:server`. then use link for ethereum claim

# Subtasks included

- [x] add componentWillReceiveProps to the component of Claiming Process Page to check that new value of transactionId is not null and not equal to previous value of transactionId.
- [x]  If you see the situation like that (new transactionId !== prev transactionId && new transactionId is not null) it means that you have to run interval to check every 3 seconds that transaction was approved and added to the blockchain after confirmations (use ethers.js library in saga file we've already created with you. you can see the reference in the get-token-data.js file)
- [x] if transaction was approved, you have to change transactionId again to null (you can see the reference in claim-tokens.js file how to change the value in store with 'USER.SET_TRANSACTION_ID' action)
- [x] you also have to add logic to componentWillReceiveProps of Claiming Process Page to check than new transactionId is null and prev transacvtionId is not null (that means that redux global state has already changed). After that you can removeInterval (use js for that and variable we stored in `this` context of component) you started for checking transaction status in the component of Claiming Process Page
- [x] after removing the interval you have to bring user to the step 5. see the reference on the page components/pages/main/index.js (find the line with comment `// page with info about current wallet and button to claim tokens` and you can see how to add this action as a property to child component, you can call this property as onFinish). if the property onFinish is available in the component, you can run it after the interval was finished.

- [x] using the existing pattern, create the same flow for erc20/erc721 tokens claim

**Comment by spacehaz** [comment]
**actions:** if you want to check actions or create new - got to data/actions folder and look for needed file. this actions can be used in each component that was wrapped by @actions decorator. if you call action function, it will dispatch action in saga or in redux, depends on where you added action name

**reducers:** if you want to check actions or create new - got to data/store/reducers folder and look for needed file. all reducers should be imported to root file in folder, and the can be used in index.js file near the action name. to check how link title of action with reducer of redux - go to data/store/reducers/user/index.js and check `const ACTIONS`


**saga-actions:** if you want to check actions or create new - got to data/store/saga/ folder and look for needed subfolders and index.js file
