### ISSUE TITLE
Improvements for link generation flow according to new mockups

### ISSUE THREAD

**Issue by spacehaz** [LinkdropProtocol/linkdrop-monorepo#94]
# addition of possibility to change networkid + to add token address manually

# Subtasks included

- [x] change networkid in link variable
- [x] add token address manually
- [x] add ERC-721 token support
